export const GET_CATEGORIES = "GET_CATEGORIES";
export const DISCOUNTED_PRODUCTS = "DISCOUNTED_PRODUCTS";
export const DELIVERY = "DELIVERY";
export const DELIVERY_NUM = "DELIVERY_NUM";
export const TOTAL_PRICE = "TOTAL_PRICE";
